version: "3"

services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"

  frontend:
    build: ./frontend
    ports:
      - "3000:80" # bonus dackerfile kullanırsan - "3000:80"
    depends_on:
      - backend
